name: "Dependabot Review Assign"
on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Last assignee'
        if: contains(github.actor, 'dependabot')
        uses: toby-daigle/rotation@v1.0.2
        with:
          members: toby-daigle jeremilc JsGarneau Pierregagne
        id: rotation
      - name: 'Add assignee'
        if: contains(github.actor, 'dependabot')
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ steps.rotation.outputs.next }}
