name: Synchronize Renovate PR with Jira

on:
  pull_request_target:
    branches:
      - master
    types:
      - closed
      - edited
      - opened
      - reopened
      - synchronize

concurrency:
  group: sync-renovate-jira

jobs:
  sync-jira:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'renovate[bot]' }}
    steps:
      - uses: equisoft-actions/jira-pr-sync@v1
        with:
          jira-url: ${{ secrets.JIRA_URL }}
          jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
          jira-user: ${{ secrets.JIRA_USER }}
          jira-project-key: ABF
          jira-transition-resolve: "To done (Bug + Story)"
          ticket-label: dependency-update
          ticket-type: "Story"
